TILE_SIZE = 64

ROUND_DURATION_SECONDS = 15
UPGRADE_CARDS_PER_ROUND = 3
ENEMY_COUNT_PER_ROUND_GROWTH = 2
STARTING_ENEMY_COUNT = 5

STARTING_MONEY = 0
ENEMY_KILL_REWARD = 15

PLAYER_BASE_DAMAGE = 1
PLAYER_BASE_HEALTH = 10
DEFAULT_HIT_INVULNERABILITY_MS = 500

TWIN_SHOT_ANGLE_OFFSET_DEGREES = 15
PIERCE_ROUNDS_EXTRA_PIERCE = 1
EXPLOSIVE_ROUNDS_RADIUS = 90
EXPLOSIVE_ROUNDS_DAMAGE = 1
VAMPIRIC_HEAL_AMOUNT = 1
ADRENALINE_SPEED_BOOST = 60
SECOND_WIND_SHIELD_CHARGES = 1
OVERCLOCK_COOLDOWN_MULTIPLIER = 0.5
OVERCLOCK_DAMAGE_MULTIPLIER = 0.7
GLASS_CANNON_DAMAGE_MULTIPLIER = 1.8
GLASS_CANNON_HEALTH_REDUCTION = 3
IRON_SKIN_INVULNERABILITY_BONUS_MS = 300

UPGRADE_CARD_WIDTH = 280
UPGRADE_CARD_HEIGHT = 340
UPGRADE_CARD_SPACING = 40
UPGRADE_CARD_CORNER_RADIUS = 12
UPGRADE_OVERLAY_ALPHA = 180
UPGRADE_TITLE_FONT_SIZE = 36
UPGRADE_BODY_FONT_SIZE = 24
UPGRADE_CARD_ACCENT_COLOURS = ["#63A375", "#4C7093", "#A3673E"]
HUD_PADDING = 20

GAME_OVER_TITLE_FONT_SIZE = 72
GAME_OVER_BODY_FONT_SIZE = 30
GAME_OVER_LINE_SPACING = 40
GAME_OVER_TOP_MARGIN = 160

PAUSE_TITLE_FONT_SIZE = 56
PAUSE_BODY_FONT_SIZE = 26
PAUSE_LINE_SPACING = 36
PAUSE_TOP_MARGIN = 100

LOGIN_TITLE_FONT_SIZE = 56
LOGIN_BODY_FONT_SIZE = 26
LOGIN_BOX_WIDTH = 320
LOGIN_BOX_HEIGHT = 48
LOGIN_FIELD_SPACING = 70
LOGIN_BUTTON_WIDTH = 220
LOGIN_BUTTON_HEIGHT = 50
LOGIN_BUTTON_SPACING = 65

LEADERBOARD_TITLE_FONT_SIZE = 56
LEADERBOARD_HEADER_FONT_SIZE = 26
LEADERBOARD_ROW_FONT_SIZE = 24
LEADERBOARD_TOP_MARGIN = 100
LEADERBOARD_ROW_SPACING = 42
LEADERBOARD_COLUMN_WIDTHS = (60, 260, 180, 180, 180)
LEADERBOARD_MAX_ROWS = 10
LEADERBOARD_SORT_OPTIONS = [
	("rounds_passed", "Rounds"),
	("kills", "Kills"),
	("time_alive", "Time Alive"),
]

MENU_LINK_FONT_SIZE = 28

ADMIN_USERNAME = "ADMIN"
ADMIN_PASSWORD = "ADM1N"
ADMIN_TITLE_FONT_SIZE = 56
ADMIN_HEADER_FONT_SIZE = 24
ADMIN_ROW_FONT_SIZE = 22
ADMIN_TOP_MARGIN = 110
ADMIN_ROW_SPACING = 40
ADMIN_MAX_ROWS = 12
ADMIN_COLUMN_WIDTHS = (50, 170, 100, 90, 100, 170)
ADMIN_DELETE_BUTTON_SIZE = 32

WEAPON_SWITCH_COOLDOWN_MS = 200
WEAPON_ICON_SIZE = 64
WEAPON_ICON_SPACING = 12
WEAPON_ICON_CORNER_RADIUS = 8
WEAPON_ORBIT_RADIUS = TILE_SIZE // 2
WEAPON_SPRITE_SHEET_PATH = "images/weapon.png"

WEAPON_DATA = {
	"pistol": {"cooldown": 400, "damage_multiplier": 1.0, "bullet_count": 1, "bullet_speed": 300, "spread_degrees": 0, "colour": "#E8D44D"},
	"shotgun": {"cooldown": 700, "damage_multiplier": 0.6, "bullet_count": 4, "bullet_speed": 260, "spread_degrees": 12, "colour": "#E87A4D"},
	"smg": {"cooldown": 150, "damage_multiplier": 0.5, "bullet_count": 1, "bullet_speed": 400, "spread_degrees": 4, "colour": "#4DA6E8"},
}

WEAPON_ICON_SPRITE_COORDS = {
	"pistol": (0, 0),
	"shotgun": (64, 0),
	"smg": (128, 0),
}

GROUND_SPRITE_COORDS = {
	"ground": (0, 768),
	"dirt": (64, 64),
	"water": (640, 768),
	"water_top_left": (704, 384),
	"water_left": (704, 448),
	"water_top": (768, 384),
	"water_top_right": (832, 384),
	"water_right": (832, 448),
}
